# Generated by Django 3.1.4 on 2021-02-11 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('desc', models.TextField(null=True)),
                ('armor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('desc', models.TextField(null=True)),
                ('max_hp', models.IntegerField(default=0)),
                ('current_hp', models.IntegerField(default=0)),
                ('firepower', models.IntegerField(default=0)),
                ('armor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventSuper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Helm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('desc', models.TextField(null=True)),
                ('armor', models.IntegerField(default=0)),
                ('sight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LeftArm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('desc', models.TextField(null=True)),
                ('armor', models.IntegerField(default=0)),
                ('firepower', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Legs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('desc', models.TextField(null=True)),
                ('armor', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RightArm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('desc', models.TextField(null=True)),
                ('armor', models.IntegerField(default=0)),
                ('firepower', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventDiscovery',
            fields=[
                ('eventsuper_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.eventsuper')),
                ('discovered', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('game.eventsuper',),
        ),
        migrations.CreateModel(
            name='EventNothing',
            fields=[
                ('eventsuper_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.eventsuper')),
            ],
            bases=('game.eventsuper',),
        ),
        migrations.CreateModel(
            name='MobileSuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('max_hp', models.IntegerField(default=0)),
                ('current_hp', models.IntegerField(default=0)),
                ('chest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.chest')),
                ('controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('helm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.helm')),
                ('left_arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.leftarm')),
                ('legs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.legs')),
                ('modifiers', models.ManyToManyField(blank=True, to='game.Modifier')),
                ('right_arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.rightarm')),
            ],
        ),
        migrations.CreateModel(
            name='EventBattle',
            fields=[
                ('eventsuper_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.eventsuper')),
                ('enemy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.enemy')),
            ],
            bases=('game.eventsuper',),
        ),
    ]
