# Generated by Django 3.1.4 on 2021-02-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='firerate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='leftarm',
            name='firerate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='rightarm',
            name='firerate',
            field=models.FloatField(default=1.0),
        ),
    ]
