# Generated by Django 3.1.4 on 2021-02-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210212_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventsuper',
            name='img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
