# Generated by Django 3.1.4 on 2021-01-22 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210122_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='helm',
            name='sight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leftarm',
            name='firepower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='legs',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rightarm',
            name='firepower',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='mobilesuit',
            name='chest',
        ),
        migrations.AddField(
            model_name='mobilesuit',
            name='chest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.chest'),
        ),
        migrations.RemoveField(
            model_name='mobilesuit',
            name='helm',
        ),
        migrations.AddField(
            model_name='mobilesuit',
            name='helm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.helm'),
        ),
        migrations.RemoveField(
            model_name='mobilesuit',
            name='left_arm',
        ),
        migrations.AddField(
            model_name='mobilesuit',
            name='left_arm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.leftarm'),
        ),
        migrations.RemoveField(
            model_name='mobilesuit',
            name='legs',
        ),
        migrations.AddField(
            model_name='mobilesuit',
            name='legs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.legs'),
        ),
        migrations.RemoveField(
            model_name='mobilesuit',
            name='right_arm',
        ),
        migrations.AddField(
            model_name='mobilesuit',
            name='right_arm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.rightarm'),
        ),
    ]
