# Generated by Django 3.1.4 on 2021-02-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210213_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='chest',
            name='img',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='helm',
            name='img',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leftarm',
            name='img',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='legs',
            name='img',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modifier',
            name='img',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rightarm',
            name='img',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
