# Generated by Django 3.1.4 on 2021-01-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210122_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trinket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='mobilesuit',
            name='trinkets',
            field=models.ManyToManyField(to='game.Trinket'),
        ),
    ]
