# Generated by Django 3.1.4 on 2021-02-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210222_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='prefix',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
