# Generated by Django 3.1.4 on 2021-02-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_enemy_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
