# Generated by Django 3.1.4 on 2021-01-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210122_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilesuit',
            name='modifiers',
            field=models.ManyToManyField(blank=True, to='game.Modifier'),
        ),
    ]
