# Generated by Django 3.1.4 on 2021-01-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20210122_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilesuit',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
