# Generated by Django 3.1.4 on 2021-01-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_mobilesuit_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilesuit',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
