# Generated by Django 3.1.4 on 2021-01-24 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_mobilesuit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilesuit',
            name='active',
        ),
    ]
