# Generated by Django 3.1.4 on 2021-01-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_mobilesuit_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
