# Generated by Django 3.1.4 on 2021-01-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_enemy'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilesuit',
            name='current_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mobilesuit',
            name='max_hp',
            field=models.IntegerField(default=0),
        ),
    ]
