# Generated by Django 3.1.4 on 2021-01-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20210126_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='armor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemy',
            name='current_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemy',
            name='firepower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemy',
            name='max_hp',
            field=models.IntegerField(default=0),
        ),
    ]
