# Generated by Django 3.1.4 on 2021-01-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20210126_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='chest',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='enemy',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helm',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='leftarm',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legs',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='modifier',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rightarm',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
